import { NavItem } from '../types';

export const NAVIGATION_ITEMS: NavItem[] = [
  {
    id: 'home',
    label: 'Home',
    sanskritLabel: 'मुख्यपृष्ठम्',
    path: '/app',
    icon: 'home',
    description: 'Sacred Gateway & Celestial Overview',
  },
  {
    id: 'kundali',
    label: 'Generate Kundali',
    sanskritLabel: 'जन्मकुण्डली',
    path: '/kundali',
    icon: 'kundali',
    description: 'Vedic Natal Horoscope & Planetary Positions',
  },
  {
    id: 'panchang',
    label: "Today's Panchang",
    sanskritLabel: 'पञ्चाङ्गम्',
    path: '/panchang',
    icon: 'panchang',
    description: 'Five Pillars of Vedic Time Keeping',
  },
  {
    id: 'muhurat',
    label: 'Muhurat',
    sanskritLabel: 'शुभमुहूर्तम्',
    path: '/muhurat',
    icon: 'muhurat',
    description: 'Auspicious Timings & Solar Hours',
  },
  {
    id: 'calendar',
    label: 'Festival Calendar',
    sanskritLabel: 'उत्सवपञ्चाङ्गम्',
    path: '/calendar',
    icon: 'calendar',
    description: 'Sacred Festivals & Tithi Events',
  },
  {
    id: 'timeline',
    label: 'Timeline',
    sanskritLabel: 'कालप्रवाहः',
    path: '/timeline',
    icon: 'timeline',
    description: 'Vimshottari Dasha & Planetary Transits',
  },
  {
    id: 'archive',
    label: 'Archive',
    sanskritLabel: 'सनातन अभिलेखागार',
    path: '/archive',
    icon: 'archive',
    description: 'Sacred Temple Library of Saved Charts & Manuscripts',
  },
  {
    id: 'settings',
    label: 'Settings',
    sanskritLabel: 'विन्यासः',
    path: '/settings',
    icon: 'settings',
    description: 'Location, Calculation Systems & Audio',
  },
  {
    id: 'about',
    label: 'About',
    sanskritLabel: 'वैदिकपरम्परा',
    path: '/about',
    icon: 'about',
    description: 'Ancient Astronomical Manuscripts & Museum',
  },
];
