import { PanchangData } from '../types/panchang';

export const TODAY_PANCHANG: PanchangData = {
  date: 'Wednesday, July 22, 2026',
  sanskritDate: '२२ आषाढ / श्रावण, विक्रम संवत् २०८३',
  location: 'Ujjain Observatory (उज्जैन)',
  vaara: {
    name: 'Wednesday (Budhavara)',
    sanskrit: 'बुधवार',
    meaning: 'Governed by Lord Budha (Mercury)',
    value: 'Budhavara',
    sanskritValue: 'बुधवारः',
    deity: 'Lord Budha (बुध)',
    progressPercent: 65,
    note: 'Favorable for intellect, calculations, trade, and learning.',
  },
  tithi: {
    name: 'Shukla Navami',
    sanskrit: 'शुक्ल नवमी',
    meaning: '9th Lunar Tithi',
    value: 'Navami (नवमी)',
    sanskritValue: 'नवमी तिथि',
    deity: 'Goddess Durga (दुर्गा)',
    endTime: 'Until 08:42 PM',
    progressPercent: 78,
    note: 'Auspicious for spiritual courage, reflection, and undertaking noble works.',
  },
  nakshatra: {
    name: 'Swati Nakshatra',
    sanskrit: 'स्वाती नक्षत्र',
    meaning: '15th Lunar Mansion',
    value: 'Swati (स्वाती)',
    sanskritValue: 'स्वाती',
    deity: 'Vayu Deva (वायु)',
    endTime: 'Until 11:15 PM',
    progressPercent: 82,
    note: 'symbolized by a young plant bending in the wind; grants flexibility & independence.',
  },
  yoga: {
    name: 'Siddha Yoga',
    sanskrit: 'सिद्ध योग',
    meaning: '21st Solar-Lunar Combination',
    value: 'Siddha (सिद्ध)',
    sanskritValue: 'सिद्ध योग',
    deity: 'Lord Kartikeya',
    endTime: 'Until 06:20 PM',
    progressPercent: 70,
    note: 'Highly auspicious for accomplishing long-term goals and meditation.',
  },
  karana: {
    name: 'Balava Karana',
    sanskrit: 'बालव करण',
    meaning: 'Half-Tithi Period',
    value: 'Balava (बालव)',
    sanskritValue: 'बालव',
    deity: 'Brahma Deva',
    endTime: 'Until 09:30 AM',
    progressPercent: 45,
    note: 'Favorable for performing sacred rituals and acts of charity.',
  },
  cycles: {
    sunrise: '05:42 AM',
    sunset: '07:18 PM',
    moonrise: '01:25 PM',
    moonset: '01:10 AM',
    solarNoon: '12:30 PM',
    sunSign: 'Cancer (कर्क)',
    moonSign: 'Libra (तुला)',
    moonPhaseName: 'Waxing Gibbous (शुक्ल पक्ष)',
    moonPhaseSanskrit: 'शुक्ल पक्ष',
    illuminationPercent: 72,
    lunarAgeDays: 8.4,
    paksha: 'Shukla Paksha (शुक्ल पक्ष)',
    lunarMonth: 'Ashadha / Shravana (आषाढ / श्रावण)',
    samvatYear: 'Vikram Samvat 2083',
    samvatName: 'Krodhi (क्रोधी)',
    ritu: 'Varsha Ritu (वर्षा ऋतु)',
    ayana: 'Dakshinayana (दक्षिणायन)',
  },
  dayCharacter: {
    title: 'The Character of Today',
    sanskritTitle: 'अद्यतन स्वभाव एवं प्रवाह',
    description:
      'This day is governed by calm reflection, disciplined intellectual effort, and spiritual clarity under the sway of Swati Nakshatra and Siddha Yoga.',
    auspiciousNote:
      'Auspicious for academic pursuits, trading calculations, writing sacred manuscripts, and evening meditation.',
    color: 'Saffron & Gold',
    element: 'Vayu (Wind)',
  },
};
